name:                           Docker tests

on:                             [push]
jobs:
  test:
    name:                       test
    runs-on:                    ubuntu-latest
    env:
      PORT:                    5000
      MONGODB_CONNECTION_STRING: mongodb://root:rootpassword@localhost:27017
      MONGODB_NAME: nettuscheduler
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2

      - name:                   Build docker compose stack
        run: |
          cd scheduler
          docker-compose -f ./integrations/docker-compose.yml up

      - name:                   Generate code coverage
        run: |
          cd scheduler
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v1
        with:
          fail_ci_if_error:     true

